name: Run onWhisper Bot

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the version you are using for the bot

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run the bot
      run: |
        python bot.py  # Run the bot (this will stop once the bot connects)
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Pass the token from GitHub Secrets
